spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
azure:
  storage:
    blob:
      connection-string: "${AZURE_STORAGE_CONNECTION_STRING}"
      container-name: "images-gallery"
